
package com.basus.fins.ui;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.Window;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;


public class PortfolioDialog extends javax.swing.JDialog implements KeyListener {
	protected static final int DIALOG_TYPE_NONE = 0;
	protected static final int DIALOG_TYPE_INFO = 1;
	protected static final int DIALOG_TYPE_ERROR = 2;
	
	// UI
	private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    
	// members
    private String message = "";
	private int type = DIALOG_TYPE_NONE;
	
    /** Creates new form JDialogError */
    public PortfolioDialog(String message, int dialogType, Component parent) {
        super((Window)parent, Dialog.ModalityType.APPLICATION_MODAL);
		this.message = message;
		if (dialogType >= DIALOG_TYPE_NONE && 
			dialogType <= DIALOG_TYPE_ERROR) {
			this.type = dialogType;
		}
        initComponents();
        this.addKeyListener(this);
		this.setErrorMessage(message);
    }
    
    static void showError(String message, Component parent) {
		(new PortfolioDialog(message, PortfolioDialog.DIALOG_TYPE_ERROR, parent)).setVisible(true);

	}
	
	static void showInfo(String message, Component parent) {
		(new PortfolioDialog(message, PortfolioDialog.DIALOG_TYPE_INFO, parent)).setVisible(true);
	}
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelMessage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setModal(true);
		if (DIALOG_TYPE_INFO == type) {
			setTitle("Info");
		}
		if (DIALOG_TYPE_ERROR == type) {
			setTitle("!!! Error !!!");
		}
        setName("PortfolioDialog");
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setPreferredSize(new java.awt.Dimension(350, 25));
        jPanel2.add(jLabelMessage);
        jLabelMessage.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jPanel2);
        
        jButtonOk.setText("OK");
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkMouseClicked(evt);
            }
        });

        jPanel3.add(jButtonOk);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        pack();
        //BtransEditor.centerComponent(this);
        jButtonOk.addKeyListener(this);
    }

    private void jButtonOkMouseClicked(java.awt.event.MouseEvent evt) {
        setDone();
    }
    
    private void setDone() {
        this.setVisible(false);
    }
    
    private void setErrorMessage(String message) {
        jLabelMessage.setText(message);
    }
    
    // keyListener implementation
    public void keyTyped(KeyEvent e) {
 	   // empty
    	if (e.getKeyChar() == KeyEvent.VK_ENTER) {
    		this.setDone();
    	}
    }
    
    public void keyPressed(KeyEvent e) {
 	   // empty
    }
    
    public void keyReleased(KeyEvent e) {
 	   // empty
    }
}
