-- $Id$

--------------------------------------------------------
-- This script loads database with a dummy account data
-- This script is supposed to be run from ij - the derby
-- client via RUN command:
-- ij> RUN 'dummy_data.sql'; 
--------------------------------------------------------
-- Create dummy account
INSERT INTO "APP"."T_ACCOUNT" (ACCOUNT_NAME,ACCOUNT_INSTITUTE_NAME,ACCOUNT_BUY_COMMISSION,ACCOUNT_SELL_COMMISSION,ACCOUNT_BASE_INDEX,ACCOUNT_CURRENCY,ACCOUNT_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE,IS_WATCHLIST) 
    VALUES ('Watchlist','',0,0,'','USD',
    'This is a special account for having assets under watch. These assets will not be included in 
portfolio summary calculations. This account cannot be removed',
    CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1);
INSERT INTO "APP"."T_ACCOUNT" (ACCOUNT_NAME,ACCOUNT_INSTITUTE_NAME,ACCOUNT_BUY_COMMISSION,ACCOUNT_SELL_COMMISSION,ACCOUNT_BASE_INDEX,ACCOUNT_CURRENCY,ACCOUNT_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE,IS_WATCHLIST) 
    VALUES ('Dummy Account','Some Brokerage',9.95,9.95,'','',
    'This is a dummy account. After setting up your accounts, please delete this account. Else, your performance and other calculations will not reflect actual values.',
    CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0);
INSERT INTO "APP"."T_ACCOUNT" (ACCOUNT_NAME,ACCOUNT_INSTITUTE_NAME,ACCOUNT_BUY_COMMISSION,ACCOUNT_SELL_COMMISSION,ACCOUNT_BASE_INDEX,ACCOUNT_CURRENCY,ACCOUNT_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE,IS_WATCHLIST) 
    VALUES ('Pseudo Account','Acme Bank',9.95,9.95,'','',
    'This is another dummy account. After setting up your accounts, please delete this account. Else, your performance and other calculations will not reflect actual values.',
    CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,0);

    
    
-- Create dummy asset data
INSERT INTO "APP"."T_ASSET" (ASSET_SYMBOL,ASSET_NAME,ASSET_QUANTITY,ASSET_BUY_DATE,ASSET_BUY_PRICE,ASSET_BUY_COMMISSION,ASSET_SELL_DATE,ASSET_SELL_PRICE,ASSET_SELL_COMMISSION,ASSET_TAX,ASSET_OTHER_COST,ASSET_LAST_SPLIT_RATIO,ASSET_LAST_SPLIT_DATE,ACCOUNT_ID,ASSET_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE) 
    VALUES ('MSFT','Microsoft',100.0000,{d '2007-11-13'},33.71,9.95,{d '2008-10-13'},24.13,9.95,0.00,0.00,0.00000,null,2,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
INSERT INTO "APP"."T_ASSET" (ASSET_SYMBOL,ASSET_NAME,ASSET_QUANTITY,ASSET_BUY_DATE,ASSET_BUY_PRICE,ASSET_BUY_COMMISSION,ASSET_SELL_DATE,ASSET_SELL_PRICE,ASSET_SELL_COMMISSION,ASSET_TAX,ASSET_OTHER_COST,ASSET_LAST_SPLIT_RATIO,ASSET_LAST_SPLIT_DATE,ACCOUNT_ID,ASSET_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE) 
    VALUES ('GOOG','Google',100.0000,{d '2008-08-18'},500.00,9.95,null,0.00,0.00,0.00,0.00,0.00000,null,2,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
INSERT INTO "APP"."T_ASSET" (ASSET_SYMBOL,ASSET_NAME,ASSET_QUANTITY,ASSET_BUY_DATE,ASSET_BUY_PRICE,ASSET_BUY_COMMISSION,ASSET_SELL_DATE,ASSET_SELL_PRICE,ASSET_SELL_COMMISSION,ASSET_TAX,ASSET_OTHER_COST,ASSET_LAST_SPLIT_RATIO,ASSET_LAST_SPLIT_DATE,ACCOUNT_ID,ASSET_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE) 
    VALUES ('YHOO','Yahoo!',200.0000,{d '2009-09-17'},33.71,9.95,{d '2010-01-12'},24.13,9.95,0.00,0.00,0.00000,null,3,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
INSERT INTO "APP"."T_ASSET" (ASSET_SYMBOL,ASSET_NAME,ASSET_QUANTITY,ASSET_BUY_DATE,ASSET_BUY_PRICE,ASSET_BUY_COMMISSION,ASSET_SELL_DATE,ASSET_SELL_PRICE,ASSET_SELL_COMMISSION,ASSET_TAX,ASSET_OTHER_COST,ASSET_LAST_SPLIT_RATIO,ASSET_LAST_SPLIT_DATE,ACCOUNT_ID,ASSET_MEMO,CREATED_ON,MODIFIED_ON,IS_ACTIVE) 
    VALUES ('APPL','Apple',50.0000,{d '2009-03-09'},78.21,9.95,null,0.00,0.00,0.00,0.00,0.00000,null,3,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);


--------------------------------
-- Test
SELECT * FROM T_ACCOUNT;
SELECT * FROM T_ASSET;

