-- $Id$

--------------------------------------------------------
-- This script creates the database schema for Portfolio
-- This script is supposed to be run from ij - the derby
-- client via RUN command:
-- ij> RUN 'schema.sql'; 
--------------------------------------------------------
-- Ignore error if the table does not exist
DROP TABLE T_ACCOUNT;
DROP TABLE T_ASSET;


-- Creates Account table
-- Account-id is auto-generated
-- Account name can be of maximum 64 character long
-- Memo field is 1024 characters max
CREATE TABLE T_ACCOUNT (
    ACCOUNT_ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT ACCOUNT_PK PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(64) NOT NULL,
    ACCOUNT_INSTITUTE_NAME VARCHAR(64) DEFAULT '',
    ACCOUNT_BUY_COMMISSION DECIMAL(5,2) DEFAULT 0.00,
    ACCOUNT_SELL_COMMISSION DECIMAL(5,2) DEFAULT 0.00,
    ACCOUNT_BASE_INDEX VARCHAR(16) DEFAULT '^GSPC',
    ACCOUNT_CURRENCY VARCHAR(4) DEFAULT 'USD',
    ACCOUNT_MEMO VARCHAR(1024) DEFAULT '',
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE SMALLINT DEFAULT 1,
    IS_WATCHLIST SMALLINT DEFAULT 0
);

-- Creates Asset table
-- Asset-id is auto-generated
CREATE TABLE T_ASSET (
    ASSET_ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT ASSET_PK PRIMARY KEY,
    ASSET_SYMBOL VARCHAR(16) NOT NULL,
    ASSET_NAME VARCHAR(64) NOT NULL,
    ASSET_QUANTITY DECIMAL(12, 4) DEFAULT 0.00,
    ASSET_BUY_DATE DATE DEFAULT CURRENT_DATE,
    ASSET_BUY_PRICE DECIMAL(8, 2) DEFAULT 0.00,
    ASSET_BUY_COMMISSION DECIMAL(5,2) DEFAULT 0.00,
    ASSET_SELL_DATE DATE DEFAULT NULL,
    ASSET_SELL_PRICE DECIMAL(8, 2) DEFAULT 0.00,
    ASSET_SELL_COMMISSION DECIMAL(5,2) DEFAULT 0.00,
    ASSET_TAX DECIMAL(5,2) DEFAULT 0.00,
    ASSET_OTHER_COST DECIMAL(5,2) DEFAULT 0.00,
    ASSET_LAST_SPLIT_RATIO DECIMAL (10, 5) DEFAULT 0,
    ASSET_LAST_SPLIT_DATE DATE DEFAULT NULL,
    ACCOUNT_ID INT NOT NULL,
    INDEX_AT_BUY_DATE DECIMAL(8, 2) DEFAULT NULL,
    INDEX_AT_SELL_DATE DECIMAL(8, 2) DEFAULT NULL,
    ASSET_MEMO VARCHAR(1024) DEFAULT '',
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE SMALLINT DEFAULT 1
);

--------------------------------
-- Test
SELECT * FROM T_ACCOUNT;
SELECT * FROM T_ASSET;
